-- Room categories, rental types/plans, status and pricing model

-- 1. Create enums
create type public.categoria_sala as enum (
  'Sala Privativa',
  'Escritório Compartilhado',
  'Consultório com Poltrona',
  'Consultório com Maca'
);

create type public.tipo_locacao as enum (
  'Locação Mensal',
  'Locação por Período'
);

create type public.status_sala as enum (
  'Disponível',
  'Indisponível',
  'Oculto'
);

-- 2. Add new columns to salas (nullable first to avoid breaking existing rows)
alter table public.salas
  add column if not exists categoria public.categoria_sala,
  add column if not exists tipo_locacao public.tipo_locacao,
  add column if not exists status public.status_sala default 'Disponível'::public.status_sala;

-- 3. Backfill categories and rental types from existing `tipo` text column (best-effort)
update public.salas
set
  categoria = case
    when tipo ilike '%Privativa%' then 'Sala Privativa'::public.categoria_sala
    when tipo ilike '%Compartilhado%' or tipo ilike '%Coworking%' then 'Escritório Compartilhado'::public.categoria_sala
    when tipo ilike '%Consultório%' then 'Consultório com Poltrona'::public.categoria_sala
    else 'Sala Privativa'::public.categoria_sala
  end,
  tipo_locacao = 'Locação Mensal'::public.tipo_locacao
where categoria is null;

-- 4. Create sala_precos table
create table if not exists public.sala_precos (
  id bigint generated by default as identity primary key,
  sala_id bigint not null references public.salas(id) on delete cascade,
  tipo_locacao public.tipo_locacao not null,
  preco numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint sala_precos_unique unique (sala_id, tipo_locacao)
);

-- 5. Enable RLS (optional, adjust to your auth rules)
alter table public.sala_precos enable row level security;

create policy "Enable read access for all users" on public.sala_precos
  for select using (true);

create policy "Enable insert for authenticated users only" on public.sala_precos
  for insert with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" on public.sala_precos
  for update using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only" on public.sala_precos
  for delete using (auth.role() = 'authenticated');
